/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.popug.accounting.messages;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TaskCreatedMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6134120769811722683L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TaskCreatedMessage\",\"namespace\":\"com.popug.accounting.messages\",\"fields\":[{\"name\":\"taskPublicId\",\"type\":\"string\"},{\"name\":\"taskName\",\"type\":\"string\"},{\"name\":\"taskDescription\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TaskCreatedMessage> ENCODER =
      new BinaryMessageEncoder<TaskCreatedMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TaskCreatedMessage> DECODER =
      new BinaryMessageDecoder<TaskCreatedMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TaskCreatedMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TaskCreatedMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TaskCreatedMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TaskCreatedMessage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TaskCreatedMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TaskCreatedMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TaskCreatedMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TaskCreatedMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence taskPublicId;
   private java.lang.CharSequence taskName;
   private java.lang.CharSequence taskDescription;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TaskCreatedMessage() {}

  /**
   * All-args constructor.
   * @param taskPublicId The new value for taskPublicId
   * @param taskName The new value for taskName
   * @param taskDescription The new value for taskDescription
   */
  public TaskCreatedMessage(java.lang.CharSequence taskPublicId, java.lang.CharSequence taskName, java.lang.CharSequence taskDescription) {
    this.taskPublicId = taskPublicId;
    this.taskName = taskName;
    this.taskDescription = taskDescription;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return taskPublicId;
    case 1: return taskName;
    case 2: return taskDescription;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: taskPublicId = (java.lang.CharSequence)value$; break;
    case 1: taskName = (java.lang.CharSequence)value$; break;
    case 2: taskDescription = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'taskPublicId' field.
   * @return The value of the 'taskPublicId' field.
   */
  public java.lang.CharSequence getTaskPublicId() {
    return taskPublicId;
  }


  /**
   * Sets the value of the 'taskPublicId' field.
   * @param value the value to set.
   */
  public void setTaskPublicId(java.lang.CharSequence value) {
    this.taskPublicId = value;
  }

  /**
   * Gets the value of the 'taskName' field.
   * @return The value of the 'taskName' field.
   */
  public java.lang.CharSequence getTaskName() {
    return taskName;
  }


  /**
   * Sets the value of the 'taskName' field.
   * @param value the value to set.
   */
  public void setTaskName(java.lang.CharSequence value) {
    this.taskName = value;
  }

  /**
   * Gets the value of the 'taskDescription' field.
   * @return The value of the 'taskDescription' field.
   */
  public java.lang.CharSequence getTaskDescription() {
    return taskDescription;
  }


  /**
   * Sets the value of the 'taskDescription' field.
   * @param value the value to set.
   */
  public void setTaskDescription(java.lang.CharSequence value) {
    this.taskDescription = value;
  }

  /**
   * Creates a new TaskCreatedMessage RecordBuilder.
   * @return A new TaskCreatedMessage RecordBuilder
   */
  public static com.popug.accounting.messages.TaskCreatedMessage.Builder newBuilder() {
    return new com.popug.accounting.messages.TaskCreatedMessage.Builder();
  }

  /**
   * Creates a new TaskCreatedMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TaskCreatedMessage RecordBuilder
   */
  public static com.popug.accounting.messages.TaskCreatedMessage.Builder newBuilder(com.popug.accounting.messages.TaskCreatedMessage.Builder other) {
    if (other == null) {
      return new com.popug.accounting.messages.TaskCreatedMessage.Builder();
    } else {
      return new com.popug.accounting.messages.TaskCreatedMessage.Builder(other);
    }
  }

  /**
   * Creates a new TaskCreatedMessage RecordBuilder by copying an existing TaskCreatedMessage instance.
   * @param other The existing instance to copy.
   * @return A new TaskCreatedMessage RecordBuilder
   */
  public static com.popug.accounting.messages.TaskCreatedMessage.Builder newBuilder(com.popug.accounting.messages.TaskCreatedMessage other) {
    if (other == null) {
      return new com.popug.accounting.messages.TaskCreatedMessage.Builder();
    } else {
      return new com.popug.accounting.messages.TaskCreatedMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for TaskCreatedMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TaskCreatedMessage>
    implements org.apache.avro.data.RecordBuilder<TaskCreatedMessage> {

    private java.lang.CharSequence taskPublicId;
    private java.lang.CharSequence taskName;
    private java.lang.CharSequence taskDescription;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.popug.accounting.messages.TaskCreatedMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.taskPublicId)) {
        this.taskPublicId = data().deepCopy(fields()[0].schema(), other.taskPublicId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.taskName)) {
        this.taskName = data().deepCopy(fields()[1].schema(), other.taskName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.taskDescription)) {
        this.taskDescription = data().deepCopy(fields()[2].schema(), other.taskDescription);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing TaskCreatedMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.popug.accounting.messages.TaskCreatedMessage other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.taskPublicId)) {
        this.taskPublicId = data().deepCopy(fields()[0].schema(), other.taskPublicId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskName)) {
        this.taskName = data().deepCopy(fields()[1].schema(), other.taskName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.taskDescription)) {
        this.taskDescription = data().deepCopy(fields()[2].schema(), other.taskDescription);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'taskPublicId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaskPublicId() {
      return taskPublicId;
    }


    /**
      * Sets the value of the 'taskPublicId' field.
      * @param value The value of 'taskPublicId'.
      * @return This builder.
      */
    public com.popug.accounting.messages.TaskCreatedMessage.Builder setTaskPublicId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.taskPublicId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'taskPublicId' field has been set.
      * @return True if the 'taskPublicId' field has been set, false otherwise.
      */
    public boolean hasTaskPublicId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'taskPublicId' field.
      * @return This builder.
      */
    public com.popug.accounting.messages.TaskCreatedMessage.Builder clearTaskPublicId() {
      taskPublicId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'taskName' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaskName() {
      return taskName;
    }


    /**
      * Sets the value of the 'taskName' field.
      * @param value The value of 'taskName'.
      * @return This builder.
      */
    public com.popug.accounting.messages.TaskCreatedMessage.Builder setTaskName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.taskName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'taskName' field has been set.
      * @return True if the 'taskName' field has been set, false otherwise.
      */
    public boolean hasTaskName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'taskName' field.
      * @return This builder.
      */
    public com.popug.accounting.messages.TaskCreatedMessage.Builder clearTaskName() {
      taskName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'taskDescription' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaskDescription() {
      return taskDescription;
    }


    /**
      * Sets the value of the 'taskDescription' field.
      * @param value The value of 'taskDescription'.
      * @return This builder.
      */
    public com.popug.accounting.messages.TaskCreatedMessage.Builder setTaskDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.taskDescription = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'taskDescription' field has been set.
      * @return True if the 'taskDescription' field has been set, false otherwise.
      */
    public boolean hasTaskDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'taskDescription' field.
      * @return This builder.
      */
    public com.popug.accounting.messages.TaskCreatedMessage.Builder clearTaskDescription() {
      taskDescription = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TaskCreatedMessage build() {
      try {
        TaskCreatedMessage record = new TaskCreatedMessage();
        record.taskPublicId = fieldSetFlags()[0] ? this.taskPublicId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.taskName = fieldSetFlags()[1] ? this.taskName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.taskDescription = fieldSetFlags()[2] ? this.taskDescription : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TaskCreatedMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<TaskCreatedMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TaskCreatedMessage>
    READER$ = (org.apache.avro.io.DatumReader<TaskCreatedMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.taskPublicId);

    out.writeString(this.taskName);

    out.writeString(this.taskDescription);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.taskPublicId = in.readString(this.taskPublicId instanceof Utf8 ? (Utf8)this.taskPublicId : null);

      this.taskName = in.readString(this.taskName instanceof Utf8 ? (Utf8)this.taskName : null);

      this.taskDescription = in.readString(this.taskDescription instanceof Utf8 ? (Utf8)this.taskDescription : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.taskPublicId = in.readString(this.taskPublicId instanceof Utf8 ? (Utf8)this.taskPublicId : null);
          break;

        case 1:
          this.taskName = in.readString(this.taskName instanceof Utf8 ? (Utf8)this.taskName : null);
          break;

        case 2:
          this.taskDescription = in.readString(this.taskDescription instanceof Utf8 ? (Utf8)this.taskDescription : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










